#Hide the mana bar if it has not changed for the set amount of time (in ticks, 1 second = 20 ticks). Set to 0 to always have it visible
#Range: 0 ~ 1200
manaHideDelay = 1
#Put the mana bar above the food/health bar (true) or else put it below (false).
manaAboveFood = true
#Put the mana bar next to the health bar (true) or else leave it next to the food bar (false).
manaByHealth = false
#The mana bar icons jitter when your current mana is low (true) or else the icons always stay put (false).
manaJitter = true
#Always show all spell slots (true) or else only show them if at least 1 spell is equipped (false).
alwaysShowSpellSlots = false

